config/routes.rb
Etsi::Application.routes.draw do
  
  root :to => 'posts#index'
  resources :posts

  match "/archives/:year(/:month)" => "archives#show", :as => :archive

end

app/models/post.rb
# encoding: utf-8
class Post < ActiveRecord::Base
  def date
    created_at.strftime("%a %_d, %h %Y")
  end

  def self.publish_years
    all.map { |post| post.created_at.year }.uniq
  end

  def self.publish_months_by_year(year)
    by_year(year).map { |post| post.created_at.month }.uniq
  end

  def self.by_year(year)
    low   = DateTime.new(year, 1)
    high  = DateTime.new((year+1), 1)
    where("created_at < ? AND created_at >= ?", high, low).order("created_at ASC")
  end

  def self.by_year_range(from, to)
    from  = DateTime.new(from)
    to    = DateTime.new(to)
    where("created_at >= ? AND created_at < ?", from, to).order("created_at ASC")
  end

  def self.by_year_month(year, month)
    if month == 12
      year = year+1
      month = 1
    end
    low  = DateTime.new(year, month)
    high = DateTime.new(year, (month+1))
    where("created_at < ? AND created_at >= ?", high, low).order("created_at ASC")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  def show
    if params[:year] and not params[:month]
      @posts = Post.by_year(params[:year].to_i)
    elsif params[:year] and params[:month]
      @posts = Post.by_year_month(params[:year].to_i, params[:month].to_i)
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.where("title LIKE ? OR content LIKE ? OR created_at LIKE ?", 
                        "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/archives/show.html.haml
#posts
  - for post in @posts
    = render(partial: 'posts/post', locals: { post: post })

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Etsi
    %meta{charset: "utf-8"}
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    #header
      %h1= link_to ("&asymp; Voluptuos Similarities &asymp;").html_safe, root_url
    #page
      %h2 Posts
      = render('shared/side')
      = yield

app/views/posts/_post.html.haml
.post
  %h3.title= post.title
  %p.content= post.content

  .meta
    %p.date= link_to(post.date, archive_path(year: post.created_at.year, month: post.created_at.month))

app/views/posts/index.html.haml
#posts
  = render(@posts)

app/views/shared/_side.html.haml
#side
  .search
    %h3 Search
    = form_tag posts_path, :method => :get do
      = label_tag :search
      = text_field_tag :search, params[:search]
      = submit_tag "L", :name => nil
  
  .data
    %h3 Data
    %p
      Posts count: 
      = @posts.count if @posts

  .archive
    %h3 Archive
    %ul
      - for year in Post.publish_years
        %li
          = link_to(year, archive_path(year: year))
          %ul
            - for month in Post.publish_months_by_year(year)
              %li= month